environment:
  my_version_number: 1.1.0 # DONT FORGET TO CHANGE IS IN THE ISS FILE

version: $(my_version_number).{build}

configuration: Release

before_build:
  - ps: nuget restore

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(my_version_number)'
  package_version: '$(my_version_number)'
  assembly_version: '$(my_version_number)'
  file_version: '$(my_version_number)'
  informational_version: '$(my_version_number)'

build:
  publish_nuget: true
  verbosity: minimal


artifacts:
  - path: /Installer/CalculatePrimesMultithreaded.exe
    name: CalcPrimesMultiThread

after_build:
  - ps: dotnet publish "-p:PublishProfile=.run\Publish framework Dependent x64.run.xml" -c:Release -o:Publish\64bit -r:win-x64 --self-contained:false
  - ps: dotnet publish "-p:PublishProfile=.run\Publish framework Dependent x86.run.xml" -c:Release -o:Publish\32bit -r:win-x86 --self-contained:false
  - ps: '& "C:\Program Files (x86)\Inno Setup 6\iscc.exe" "Deployment\Inno Config.iss"'

deploy:
  - provider: GitHub
    release: $(my_version_number)
    auth_token: # encrypted token:
      secure: HESVuhwKdUbPpbBsQrWslB7GYNy5r03/MN/enpu7UWbY886bOE+EpbEFwAVMrtLO
    artifact: CalcPrimesMultiThread
    draft: false
    prerelease: false
    force_update: false
    on:
      branch: master